### ISSUE TITLE
Date field withMin and withMax showing errors when valid date is input

### ISSUE THREAD

**Issue by RGBboy** [dillonkearns/elm-form#1]
I saw your post on the Elm Discourse and had a little play with the [Ellie you linked](https://ellie-app.com/myVVqSVC2QZa1). Great work! 

I did however find a bug in the example when using `Field.withMin` with date fields. See line 319 from the example `Field.withMin today ("Must be after " ++ Date.toIsoString today)`. When I input a date that is after today I am shown an error. Seems like the same happens when using withMax and inputting a date before the passed date. 

From my quick investigation it seems like the problem comes from the order of comparing `raw` and `value` [here](https://github.com/dillonkearns/elm-form/blob/768be8d097bb7c7c738c21c74c7776e0020d2214/src/Form/Field.elm#L380)

I may be wrong but I think this block should be:

```elm
Result.map2 Date.compare
  (Date.fromIsoString raw)
  (Ok value)
  |> Result.withDefault LT
```

**Comment by dillonkearns** [comment]
Thank you for opening the issue! This is fixed in the [2.0.2 release](https://github.com/dillonkearns/elm-form/blob/main/CHANGELOG.md#202---2023-04-18) 👍
