### ISSUE TITLE
Documentation shows function that doesn't exist

### ISSUE THREAD

**Issue by Confidenceman02** [dillonkearns/elm-form#7]
In the [Form](https://package.elm-lang.org/packages/dillonkearns/elm-form/latest/Form) documentation I'm seeing a `withClientValidation` function being used as an example but I can't seem to find it in the actual code.

I'm assuming this is a typo or perhaps relates to `elm-pages`?

Im intending to create a PR fixing this but just wanted to make sure.

**Comment by dillonkearns** [comment]
Hey @Confidenceman02, thanks for confirming. That's correct, that function no longer exists. A PR to clean that up would be very welcome. Thank you!

**Comment by shahnhogan** [comment]
@dillonkearns maybe this can be closed -- I don't see `withClientValidation` in the docs any longer.

**Comment by dillonkearns** [comment]
Sounds good, thanks for checking!
